Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,7 +17,9 @@ jobs:
       mysql:
         image: mysql:5.7
         env:
+          MYSQL_ALLOW_EMPTY_PASSWORD: false
           MYSQL_ROOT_PASSWORD: root
+          MYSQL_DATABASE: test_unit
         ports:
           - 3306:3306
         options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
@@ -74,6 +76,16 @@ jobs:
       - name: Static analysis of PHP code
         run: |
           php bin/console about --env=prod
+          
+      ## —— BDD —————————————————————————————————————————————————  
+      - name: Run bdd
+        run: |
+            composer require --dev symfony/orm-pack
+            php bin/console doctrine:database:drop --if-exists --force --env=test
+            php bin/console doctrine:database:create --if-not-exists --env=test
+            php bin/console doctrine:schema:update --env=test --force || echo "No migrations found or schema update failed"
+        env:
+           DATABASE_URL: mysql://root:root@127.0.0.1:${{ job.services.mysql.ports['3306'] }}/test_unit
 
       ## —— Tests ✅ ———————————————————————————————————————————————————————————
       # We use the dev env here
